language: java
install: ant deps
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start" # this is a virtual screen
  - sleep 3 # give xvfb some time to start
script: ant main
jdk:
  - oraclejdk8
notifications:
  slack: husacct:dzyOOT9XxkAKgVhRg5I72WSo`

